# -*- coding: utf-8 -*-
"""Text-Gemma-4-E2B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmCjjcb6sbzBZHX7F5odhhi1oxKUnp5U
"""

!nvidia-smi

!pip install -q -U "transformers>=5.5.0" accelerate bitsandbytes
!pip install -q librosa soundfile pillow
!pip install -q -U huggingface_hub

from huggingface_hub import login

# Option A: interactive — paste token when prompted
login()

# Option B: Colab secrets (uncomment if using)
# from google.colab import userdata
# login(token=userdata.get('HF_TOKEN'))

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText

MODEL_ID = "google/gemma-4-E2B-it"

processor = AutoProcessor.from_pretrained(MODEL_ID)

model = AutoModelForImageTextToText.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,     # T4 prefers fp16 over bf16
    device_map="auto",
).eval()

print(f"Model loaded. Device: {model.device}")
print(f"VRAM used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

def generate(messages, max_new_tokens=512, thinking=False):
    """Run the model on a chat-formatted messages list."""
    # Optionally prepend the thinking control token to the system prompt
    if thinking:
        sys_msg = {"role": "system", "content": [{"type": "text", "text": "<|think|>"}]}
        messages = [sys_msg] + messages

    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device)

    input_len = inputs["input_ids"].shape[-1]

    with torch.inference_mode():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
        )

    generated = out[0][input_len:]
    return processor.decode(generated, skip_special_tokens=True)

# with torch.inference_mode():
#     out = model.generate(
#         **inputs,
#         max_new_tokens=max_new_tokens,
#         do_sample=False,
#         top_p=None,    # explicitly unset
#         top_k=None,    # explicitly unset
#     )

text_messages = [
    {"role": "user", "content": [
        {"type": "text", "text":
            "A hospital's ED saw 1,240 presentations last week. 68% were seen within "
            "4 hours. Among the remaining, 40% breached due to bed block. "
            "How many patients breached due to bed block? Show your reasoning."
        }
    ]},
]

print(generate(text_messages, max_new_tokens=300))

print(generate(text_messages, max_new_tokens=800, thinking=True))

